///////////////////////////////////////////////////
//      SHOTGUN FRENZY
//   a mod by Wad'a'Holic

// f_Price.acs
// quick price setup

#library "fl_Price"
#include "zcommon.acs"

int f_Price[499];	// up to 499 items can be brought

// easier way to customise the prices (with a script)
script 900 OPEN
{
    f_Price[0]=     0;      // (ignored)
    f_Price[1]=     2500;      // Genetics Lab
    f_Price[2]=     2500;      // Armory
    f_Price[3]=     8500;      // Marine Command (NOW MECH FACTORY)
    f_Price[4]=     3500;      // Refinery
    f_Price[5]=     5500;      // Demonic Lab (NOW MARINE COMMAND)
    f_Price[6]=     15000;      // Nuclear Silo
    f_Price[7]=     0;      // 
    f_Price[8]=     0;      // 
    f_Price[9]=     0;      // 
    f_Price[10]=    0;      // 
    f_Price[11]=    0;      // 
    f_Price[12]=    1000;      // Human Engineering Phase 1
    f_Price[13]=    2000;      // Human Engineering Phase 2
    f_Price[14]=    0;      // 
    f_Price[15]=    1500;      // Adrenaline
    f_Price[16]=    1500;      // Steel Plating
    f_Price[17]=    2000;      // Resister Unit
    f_Price[18]=    2000;      // Asorber Unit
    f_Price[19]=    150;      // Soulsphere
    f_Price[20]=    300;      // Megasphere
    f_Price[21]=    2850;      // Godsphere
    f_Price[22]=    1850;      // Berserk 2.0
    f_Price[23]=    3850;      // Personal Backpack
    f_Price[24]=    0;      //  
    f_Price[25]=    4900;      // Grunt Backpack
    f_Price[26]=    1500;      // Arms Phase 1
    f_Price[27]=    2000;      // Arms Phase 2
    f_Price[28]=    2000;      // Boomshot Rounds
    f_Price[29]=    1500;      // Ammo Backpack
    f_Price[30]=    100;      // Construct Sandbags
    f_Price[31]=    500;      // Construct Minefield
    f_Price[32]=    800;      // Construct Ammo Dispenser
    f_Price[33]=    800;      // Construct Health Dispenser
    f_Price[34]=    2300;      // Shotgunner Backpack
    f_Price[35]=    2500;      // Assault Backpack
    f_Price[36]=    350;      // Support Backpack
    f_Price[37]=    5250;      // Heavy Backpack
    f_Price[38]=    5250;      // Plasma Backpack
    f_Price[39]=    9850;      // Flamethrower
    f_Price[40]=    800;      // Construct Bullet Turret
    f_Price[41]=    1300;      // Construct Rocket Turret
    f_Price[42]=    1300;      // Construct Plasma Turret
    f_Price[43]=    1000;      // Construct Rail Turret
    f_Price[44]=    1200;      // Advanced Systems
    f_Price[45]=    1200;      // Construct Shotgun Turret
    f_Price[46]=    1800;      // Construct Telsa Turret
    f_Price[47]=    2500;      // Construct Flame Turret
    f_Price[48]=    850;      // Drone Tech
    f_Price[49]=    100;      // Mine Drone
    f_Price[50]=    350;      // Saw Drone
    f_Price[51]=    0;      // Turret Drone
    f_Price[52]=    12000;      // Spawn Tank 	10000
    f_Price[53]=    4000;      // Ion Heat
    f_Price[54]=    4000;      // Air Support
    f_Price[55]=    0;      // Motion Tracking
    f_Price[56]=    4500;      // Processing Phase 1
    f_Price[57]=    4500;      // Processing Phase 2
    f_Price[58]=    0;      // Entering Tank
    f_Price[59]=    0;      // Exiting Tank
    f_Price[60]=    500;      // Summon pack of Lost Souls
    f_Price[61]=    500;      // Summon pack of Pinky Demons
    f_Price[62]=    900;      // Summon Revenant
    f_Price[63]=    1200;      // Summon Hell Knight
    f_Price[64]=    2200;      // Summon Baron of Hell
    f_Price[65]=    5000;      // Summon Cyberdemon
    f_Price[66]=    500;      // Pulse Rage (was 2000)
    f_Price[67]=    900;      // Cripple Pulse
    f_Price[68]=    500;      // Halt Pulse
    f_Price[69]=    3000;      // Core Revive
    f_Price[70]=    0;      // Repair tank
    f_Price[71]=    1200;      // Stimpacks 
    f_Price[72]=    18000;      // EXTRA BACKPACK: BFG 9000
    f_Price[73]=    0;      // 
    f_Price[74]=    0;      // 
    f_Price[75]=    0;      // Nuclear Attack
    f_Price[76]=    850;      // Airstrike
    f_Price[77]=    0;      // Minestrike
    f_Price[78]=    0;      // Detonate all mines
    f_Price[79]=    0;      // Fire Ion Cannon
    f_Price[80]=    2500;      // Money bag
    f_Price[81]=    0;      // Attack
    f_Price[82]=    0;      // Defend
    f_Price[83]=    0;      // Construct
    f_Price[84]=    0;      // Regroup
    f_Price[85]=    0;      // 
    f_Price[86]=    4000;      // Mech weapons upgrade 1	4000
    f_Price[87]=    0;      // 
    f_Price[88]=    0;      // 
    f_Price[89]=    0;      // 
    f_Price[90]=    5000;      // Mech armor upgrade 1	5000
    f_Price[91]=    5000;      // 
    f_Price[92]=    800;      // Deployable Health Dispenser
    f_Price[93]=    800;      // Deployable Ammo Dispenser
    f_Price[94]=    300;      // Deployable Marine Mine
    f_Price[95]=    800;      // Deployable Turret Bullet
    f_Price[96]=    1300;      // Deployable Turret Rocket
    f_Price[97]=    1300;      // Deployable Turret Plasma
    f_Price[98]=    1000;      // Deployable Turret Rail
    f_Price[99]=    2500;      // Deployable Turret Flame
    
    f_Price[401]=    700;      // barricade #1 - Floor rise (attached to tag 51)
    f_Price[402]=    1000;      // barricade #2 - Floor rise (attached to tag 52)
    f_Price[403]=    1300;      // barricade #3 - Floor rise (attached to tag 53)
    f_Price[404]=    300;      // barricade #3 - Floor rise (attached to tag 54)
}    